language: go
services:
- docker
matrix:
  include:
  - go: 1.12.x
    script:
    - make test-go
  - language: python
    python: 3.7-dev
    env:
    - PATH=/opt/go/bin:${PATH}
    - GOROOT=/opt/go
    install:
    - curl -LO https://dl.google.com/go/go1.12.linux-amd64.tar.gz
    - tar xzf go1.12.linux-amd64.tar.gz -C /opt
    - pip install pipenv
    - make python-deps
    script:
    - make test-py
env:
  global:
    - GO111MODULE=on
